import { NextPage } from 'next'
import { Html, Head, Main, NextScript } from 'next/document'

const Document: NextPage = () => {
  return (
    <Html>
      <Head>
        <meta name="description" content="Andrés Segura" />
        <link rel="icon" href="/favicon/favicon.ico" />
        {/**----------------------------------------------------- */}
        <meta property="og:type" content="article" />
        <meta property="og:title" content="Andrés Segura" />
        <meta property="og:description" content="desarrolladores dev" />
        <meta property="og:image" content="https://raw.githubusercontent.com/Andr7st/Andr7st/main/own/icon/logo-og.png" />
        <meta property="og:url" content="desarrolladores" />
        <meta property="og:site_name" content="desarrolladores dev" />
        {/**----------------------------------------------------- */}
        <meta name="twitter:title" content="Andrés Segura" />
        <meta name="twitter:description" content="desarrolladores dev" />
        <meta name="twitter:image" content="https://raw.githubusercontent.com/Andr7st/Andr7st/main/own/icon/logo-og.png" />
        <meta name="twitter:site" content="@Andr7st" />
        <meta name="twitter:creator" content="@Andr7st" />
        <link rel="apple-touch-icon" href="https://raw.githubusercontent.com/Andr7st/Andr7st/main/own/icon/logo-og.png" />
        {/**----------------------------------------------------- */}
        <link rel="apple-touch-icon-precomposed" sizes="57x57"   href="/favicon/apple-touch-icon-57x57.png" />
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/favicon/apple-touch-icon-114x114.png" />
        <link rel="apple-touch-icon-precomposed" sizes="72x72"   href="/favicon/apple-touch-icon-72x72.png" />
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/favicon/apple-touch-icon-144x144.png" />
        <link rel="apple-touch-icon-precomposed" sizes="60x60"   href="/favicon/apple-touch-icon-60x60.png" />
        <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/favicon/apple-touch-icon-120x120.png" />
        <link rel="apple-touch-icon-precomposed" sizes="76x76"   href="/favicon/apple-touch-icon-76x76.png" />
        <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/favicon/apple-touch-icon-152x152.png" />
        <link rel="icon" type="image/png" href="/favicon/favicon-196x196.png" sizes="196x196" />
        <link rel="icon" type="image/png" href="/favicon/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/png" href="/favicon/favicon-32x32.png" sizes="32x32" />
        <link rel="icon" type="image/png" href="/favicon/favicon-16x16.png" sizes="16x16" />
        <link rel="icon" type="image/png" href="/favicon/favicon-128.png" sizes="128x128" />
        {/**----------------------------------------------------- */}
        <meta name="application-name" content="desarrolladores"/>
        <meta name="msapplication-TileColor" content="#FFFFFF" />
        <meta name="msapplication-TileImage" content="/favicon/mstile-144x144.png" />
        <meta name="msapplication-square70x70logo"   content="/favicon/mstile-70x70.png" />
        <meta name="msapplication-square150x150logo" content="/favicon/mstile-150x150.png" />
        <meta name="msapplication-wide310x150logo"   content="/favicon/mstile-310x150.png" />
        <meta name="msapplication-square310x310logo" content="/favicon/mstile-310x310.png" />
        {/** <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" /> */}
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        {/** For Material Ui: */}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>
      <body>
        <Main />
        <NextScript />
        {/**please use defer or async if you want to import a script */}
      </body>
    </Html>
  )
}

export default Document